// Generated by scripts/generate-component-metadata.mjs from apps/docs/scripts/blocks.json. Do not edit.

export const BLOCK_METADATA = [] as const;

export type BlockMetadata = (typeof BLOCK_METADATA)[number];
export type BlockSlug = BlockMetadata['slug'];
